### ISSUE TITLE
Host: add property page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#100]
As a host you have the ability to add a property after login. 

The design for this page is [here ](https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1191%3A1329&scaling=min-zoom)

The database structure was created with #81 

The design is implemented here https://ajutordeurgenta.ro/host/accommodation/add 

The availability for each property will be handled with a different issue see #64. 

With this issue we should give hosts the ability to add a property.
We should validate all date as much as it makes sense.

**Comment by andreisusanu** [comment]
Implemented. Ready for QA.
