### ISSUE TITLE
Host: list properties

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#101]
We should implement the list properties pages as shown in the design [here ](https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1191%3A1271&scaling=min-zoom).

Html implementation here https://ajutordeurgenta.ro/host/accommodation 

We should paginate the properties, six per page.

**Comment by andreisusanu** [comment]
TODO: implement pagination - WIP

**Comment by andreisusanu** [comment]
Pagination implemented.
