### ISSUE TITLE
Host: property details page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#102]
With #101 we have listed the properties. Here we should show the property details. 

Figma design here https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1191%3A1882&scaling=min-zoom 

Implemented HTML here https://ajutordeurgenta.ro/host/accommodation/view 

We should add the edit button in the top right corner, as shown in figma.

**Comment by andreisusanu** [comment]
Implemented. Ready for QA.
