### ISSUE TITLE
Host: edit property page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#103]
With #102 he have implemented the details page and with #101 the list page. 

We now have to implement the edit page. 

Here we will have the same fields as in Add Property #100 .

Figma design here https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1191%3A1329&scaling=min-zoom

**Comment by andreisusanu** [comment]
Implemented. Ready for QA.
