### ISSUE TITLE
Design: implement admin dashboard

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#113]
We need to implement the design for admin dashboard as shown in figma 

https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1194%3A2491&scaling=min-zoom

For charts we will most likely use https://www.chartjs.org/ but you can add an image as placeholder for now.

**Comment by nickraileanu** [comment]
done on development
