### ISSUE TITLE
Host images served from app url 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#123]
Instead of s3 link use app url

**Comment by andreisusanu** [comment]
It's buggy, the images are not displayed properly when using lightbox.

![image](https://user-images.githubusercontent.com/2534555/91290802-c5f05d80-e79c-11ea-81af-5cd9da942fd6.png)

**Comment by andreisusanu** [comment]
Fix in progress...

**Comment by andreisusanu** [comment]
Bug fixed. Ready to be tested.

**Comment by andreisusanu** [comment]
Move route under Auth middleware.
Change URL to use hash instead of predictable IDs.

**Comment by andreisusanu** [comment]
Fixed. @mariusghitoiu

**Comment by mariusghitoiu** [comment]
Looks good.
