### ISSUE TITLE
Make sure email used everywhere is ajutor@asociatiamame.com

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#126]
Contact form. 
From for all emails. : ajutor@asociatiamame.com

**Comment by wasile** [comment]
We need to update onepassword credentials values. Andrei updated the github secrets for MAIL_FROM_ADDRESS and MAIL_FROM_NAME @mariusghitoiu

**Comment by mariusghitoiu** [comment]
MAIL_FROM_ADDRESS - I have changed this back to no-reply@ajutordeurgent.ro until we validate in sendgrid asociatiamame.com domain.

**Comment by mariusghitoiu** [comment]
> We need to update onepassword credentials values. Andrei updated the github secrets for MAIL_FROM_ADDRESS and MAIL_FROM_NAME @mariusghitoiu

Updated in 1password by Andrei.

**Comment by mariusghitoiu** [comment]
Done.
