### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#135]
We need to add a contact page with a contact form. 

**Fields:**
First name & last name: text 
Email Address: text 
Phone (optional) - text
Message - textarea 
Checkbox: _Sunt de acord cu GDPR._

Once submitted we show a nice message like this in the page: 
_Mesajul dumneavoastră a fost trimis cu succes.
Vă multumim!_
and send the form content to ajutor@asociatiamame.com

**Comment by wasile** [comment]
http://helpforhealth.local/ro/get-involved

**Comment by mariusghitoiu** [comment]
@wasile avem urmatoarele validari nenecesare la contact form: 

- adresa de email unica. Nu trebuie sa comparam cu tabelul de useri, cineva cu un email poate scrie de mai multe ori. 
- la text limita superioada trebuie mai mare de 64 caractere. As zice 10000
