### ISSUE TITLE
Menu updates for logged in users

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#146]
**Frontend**
- add link to my profile page. 

**Admin**
- add link to My profile and 2 FA. 

Also in My profile page for host we should add a new box for 2FA after **Datele de logare in cont**
We should show a text only saying if 2FA is activated or not and a button to activate or deactivate. 

I am thinking now that it makes more sens for the 2FA configuration page to be with the admin layout instead of the frontend one, because the same layout is used for edit profile as well. 
https://dev.ajutordeurgenta.ro/ro/2fa

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
<img width="393" alt="Screen Shot 2020-09-21 at 12 12 15 PM" src="https://user-images.githubusercontent.com/147089/93750149-b3364080-fc03-11ea-94fc-d82202225f0d.png">

@andreipetcu we need to add My Profile and 2FA links for admin menu as well.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
Looks good.
