### ISSUE TITLE
Implement design for `Solicita Servicii` flow

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#15]
We need to implement the design for the "Request Services" flow. 

We have a form with multiple steps. 

See the design here https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1106%3A3776&scaling=min-zoom

Make sure to check SMS and Accommodation to see all steps.

**Comment by nickraileanu** [comment]
done on development
