### ISSUE TITLE
2FA updates

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#156]
We need to do the following regarding the 2FA: 

- [x] On login, when the 2FA code is required we should keep the frontend layout for this page. We show the admin layout only when we setup the 2FA. 

- [x] If a user has 2FA activated after login, before providing the 2fa code should not be able to access pages that require logins like https://ajutordeurgenta.ro/host/accommodation
https://ajutordeurgenta.ro/host/accommodation/add 
or edit accommodation.

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
@andreipetcu something went wrong here. 
<img width="1879" alt="Screen Shot 2020-09-23 at 11 05 35 PM" src="https://user-images.githubusercontent.com/147089/94063829-60ba7700-fdf1-11ea-915d-bbcfde9736b5.png">

**Comment by andreipetcu** [comment]
Done on development

**Comment by mariusghitoiu** [comment]
Looks good now.
