### ISSUE TITLE
Delete user data

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#158]
We need  to give the admin the possibility to delete users. Once a user is deleted the following should happen: 

- [ ] soft delete the user. Make sure soft deleted users are not shown in the interface. 

- [ ] change user email with a random email address @example.com 

- [ ] Replace first and last name with random names generated with maybe faker. 

- [ ] Replace phone number with 10 random digits starting with 07 

- [ ] Remove county and city from user profile.

**Comment by andreipetcu** [comment]
Done on development branch

soft deleted:
- users
- accommodations
- help_resources
- help_resource_type

anonymized:
- users
- accommodations
- help_resources

**Comment by mariusghitoiu** [comment]
@andreipetcu when I delete a host I get this error. 
<img width="1414" alt="Screen Shot 2020-10-04 at 9 12 28 PM" src="https://user-images.githubusercontent.com/147089/95023552-5e280f00-0686-11eb-8113-973bb81ee1c4.png">

**Comment by andreipetcu** [comment]
Fixed on development branch

**Comment by mariusghitoiu** [comment]
Works as expected.
