### ISSUE TITLE
Updates parteners

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#163]
In partners page we should change a bit the partners boxes design as shown in the attached image:
(ignore the section above with title and text). 
Because here the background is white, they will have to add some partners twice, once for homepage and once for partners page
- [ ] links should open in a new tab, and require rel="noopener". Make sure it is the same on homepage as well. 

![Parteneri](https://user-images.githubusercontent.com/147089/94166555-1e964180-fe94-11ea-914e-350627025ca6.png)

**Comment by andreipetcu** [comment]
Done on development branch

**Comment by mariusghitoiu** [comment]
<img width="999" alt="Screen Shot 2020-10-04 at 8 50 16 PM" src="https://user-images.githubusercontent.com/147089/95023015-426f3980-0683-11eb-8deb-5d152eb16054.png">
@andreipetcu I think text background should be blue here, see the screenshot in issue description.

**Comment by andreipetcu** [comment]
Done on development branch.

**Comment by mariusghitoiu** [comment]
Looks good now.
