### ISSUE TITLE
Fix phone number on edit 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#171]
For user profile, clinics and everywhere in admin where we use it. 

**Update**
- we will save the prefix separately in the database with a connection to countries table, where we have the prefix. Something like `phone_country_id`

**Comment by andreipetcu** [comment]
Done on development

**Comment by andreipetcu** [comment]
Done on issues/171_fix_phone branch

**Comment by mariusghitoiu** [comment]
Deployed on live. Looks good!
