### ISSUE TITLE
Feedback Technology Security - more audit logs

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#188]
We want to implement laravel auditing to have mode details about who edit what and when.
https://github.com/owen-it/laravel-auditing

We should also make logs accessible for admins.
We will use Datatable with server side processing.
https://github.com/yajra/laravel-datatables

**Comment by andreipetcu** [comment]
Done on issues/188_audit_logs branch

**Comment by mariusghitoiu** [comment]
Deployed on live. Looks good.
