### ISSUE TITLE
Feedback Technology Security - log successful and failed login attempt

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#189]
We need to know the following: 

- [ ] When was the last successful login for a user

- [ ] When an how many failed login attempts there were 

- [ ] Show a log for admins with login attempts. 

Useful links: 
https://laravel.com/docs/7.x/authentication#events
https://brayniverse.com/monitoring-failed-login-attempts-with-laravel.html

**Comment by andreipetcu** [comment]
Done on issues/188_audit_logs branch

**Comment by mariusghitoiu** [comment]
Deployed on live. Looks good.
