### ISSUE TITLE
Request help flow

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#19]
We now have the design for request help flow with #15. We now need to implement the functionality

- [x] We should show the second step only if the sms checkbox was checked. 

- [x] We should show the third step only if the accommodation box was checked. 

At the end we should show a thank you page. 
Data goes in the database following the structure created with #3

**Comment by andreisusanu** [comment]
Main form implemented, fully functional, with validation and model saving.

Left to do: 
- store selected request types
- SMS section
- accomodation section

**Comment by andreisusanu** [comment]
Implemented.

WIP: translations

**Comment by andreisusanu** [comment]
Implemented. Ready to be tested.

**Comment by andreisusanu** [comment]
Focus the first section that contains validation errors.

**Comment by andreisusanu** [comment]
remove has-sms, has-accommodation

**Comment by andreisusanu** [comment]
Improvements implemented.

**Comment by mariusghitoiu** [comment]
@andreisusanu we need to make sure at least one option from "Cu ce putem să te ajutăm?" is selected.

**Comment by mariusghitoiu** [comment]
Fixed and deployed.
