### ISSUE TITLE
Create Database Structura

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#3]
Starting from the frontend and backend design from here 
https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1106%3A2654&scaling=min-zoom
and 
https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1194%3A2491&scaling=min-zoom

We should create a first version of the database scheme to start with. 

This should be created with migrations. 

It doesn't not have to have everything to start with, but a good structure on which we can build moving forward.

**Comment by andreisusanu** [comment]
`clinics`
- id
- name
- description
- additional_information
- transport_details
- country_id
- city (name, freestyle)
- address
- phone_number (text, freestyle)
- website
- contact_person_name
- contact_person_phone
- contact_person_email

`specialities`
- id
- name
- description
- parent_id (nullable)

`clinic_speciality`
- id
- clinic_id
- speciality_id

`help_requests` - CERERE
- id
- patient_full_name
- patient_phone_number
- patient_email
- caretaker_full_name
- caretaker_phone_number
- caretaker_email
- county_id (siruta)
- city_id (siruta)
- diagnostic
- extra_details
- status (nou, finalizat, in progress)

`help_request_notes`
- id
- help_request_id
- message

`help_types`
- id
- name

`help_request_type`
- id
- help_request_id
- help_type_id
- approve_status (aprobat / refuzat)
- message (nullable) - for Other type

`help_request_sms_details`
- id
- help_request_id
- amount
- purpose (freestyle)
- clinic_id ?
- country_id
- city (freestyle text)

`help_request_accomodation_details`
- id
- help_request_id
- clinic_id ?
- country_id
- city (freestyle text)
- guests_number
- start_date
- end_date
- special_request (freestyle text)

**Comment by andreisusanu** [comment]
Discussed models are now implemented.

To be continued with: Resources, Accomodations, Hosts(?)

**Comment by mariusghitoiu** [comment]
Done. For accommodation see #81
