### ISSUE TITLE
Design: Thank you page for Request Help for 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#35]
We need to implement the design of the thank you page after the form from #19 is submitted. 

See the design in figma here https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1106%3A4345&scaling=min-zoom

- [x] Create a thank you page @andreisusanu 

- [x] Implement the design of the page @nickraileanu

**Comment by andreisusanu** [comment]
https://ajutordeurgenta.ro/ro/request-services-thanks
