### ISSUE TITLE
Design: Implement Get involved page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#36]
We need to implement the design for Get Involved Page 

Page here: https://ajutordeurgenta.ro/ro/get-involved 

Design here: https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1106%3A3408&scaling=min-zoom

As always, make sure it looks good on mobile as well. 

Make sure you add both cases with **Accommodation** is checked and **Other** - see figma

**Comment by nickraileanu** [comment]
done on development
