### ISSUE TITLE
Design: Admin - clinics and clinics categories management 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#39]
We need to build the pages to manage clinics and clinics categories in admin 
https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1196%3A4374&scaling=min-zoom

@andreisusanu 

- [x] Please add the dummy views for these

@nickraileanu 
- [x] once we have the views you can start on the design.

**Comment by nickraileanu** [comment]
done on development

**Comment by nickraileanu** [comment]
I think this is done
