### ISSUE TITLE
Admin: List requests for help

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#41]
With #19 we have implemented the request for help forms. 

With this issue we want to show all these requests in admin, only for administrator role.

The design can be found here: 
https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1196%3A6719&scaling=min-zoom

**For now we should show:** 
- ID 
- Nume & prenume Pacient 
- Nume & prenume Solicitant. 
- Diagnostic 
- Data solicitarii
- Status
- Nivel de Aprobare - Will be removed.
- Actiuni (Delete) - Will be removed from the grid.
- Details (link to details) 

Use Ajax to load the page. 

Search will be done in #65

As filters we should have:
- status
- start date
- end date 
- search field

On change should reload the page automatically.

- Sort the entries, by created at DESC.

- [ ] Implement the design of the page -  @nickraileanu 

- [ ] Implement the above described functionalities for this page - @andreisusanu

**Comment by andreisusanu** [comment]
Ready to be tested.

**Comment by mariusghitoiu** [comment]
Looks good. Search will be done in #65
