### ISSUE TITLE
Admin: request for help details page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#42]
With #41 we have a list with requests for help. 
With this issue we want to handle the details page. 

@nickraileanu 
- [x] Remove Nivel de aprobare from Detalii cerere section.
- [x] The Status field will be text, instead of dropdown.
- [x] The design of this page can be found here
https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1291%3A296&scaling=min-zoom

- [x] We should implement a confirmation popup. We will show one when changing the status of the request. 

- [x] We should also implement the "Adauga nota" popup. We will use [Tinymce](https://www.tiny.cloud/) editor. 

@andreisusanu 

- [x] We should show the details as show in the design. 

- [x] For each type of solicitation checked in form we show a box. 

- [x] On each type of solicitation admin will only be able to change "Nivel de aprobare". See #43 

- [x] The status of the request should change automatically, see #44

**Comment by nickraileanu** [comment]
Status field should be input type text? 

If so, we will also need a button to apply that change from the input.

**Comment by mariusghitoiu** [comment]
No, just text. It will update automatically. We only need to display it.

**Comment by nickraileanu** [comment]
Who will update it? From where?

**Comment by mariusghitoiu** [comment]
"Nivel de aprobare" on Each solicitation, is a drop down (see it in figma after the notes screens). When this is changed the reequest status is affected. See issue #43

**Comment by nickraileanu** [comment]
I've added 3 badges on 'detalii cerere' - 'in asteptare', 'aprobata', 'neaprobata' and implemented a confirm dialog when status is changed

**Comment by andreisusanu** [comment]
Functionality implemented. Ready to be tested.
