### ISSUE TITLE
Admin: Implement Notes functionality on help requests

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#45]
From #42 you can add notes to a Help request. 

With this issue we should: 
- [x] Implement de design for notes - see https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1291%3A833&scaling=min-zoom

- [x] Implement the functionality of adding and showing notes. 
  - should be connected with the request 
  - are available only for admins 
  - can be soft deleted by admin 
  - even if not shown in the design, we should show the date/time when was added and by whom. @nickraileanu please include these as well when implementing the design.
  - order them by date ASC.  
  - can be edited.

**Comment by andreisusanu** [comment]
Ready to be tested.
