### ISSUE TITLE
Admin: Implement Add new clinic page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#46]
We should implement the add new clinic page. 

- [x] Design is here @nickraileanu https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1196%3A5465&scaling=min-zoom

- [x] We should implement the form with all necessary validations. After save should redirect to index #47

**Comment by andreisusanu** [comment]
Implemented. Ready to be tested.

**Comment by mariusghitoiu** [comment]
Looks good.
