### ISSUE TITLE
Admin: implement clinics list page

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#47]
The design of this page is very similar to what we have on frontend. We should only adapt it to the admin layout 

- [x] We should adapt the design @nickraileanu https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1196%3A4374&scaling=min-zoom

- [ ] We should implement the functionalities.

**Comment by nickraileanu** [comment]
clinics list page layout implemented on development

**Comment by mariusghitoiu** [comment]
Done. Search will be handled here https://github.com/code4romania/help-for-health/issues/78
