### ISSUE TITLE
Admin: clinics categories 

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#51]
- [x] We should implement the design of all related pages in admin https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1196%3A5640&scaling=min-zoom 

**Functionalities**

- [x] We should have a three, with parent_id for each category. If parent is null that is a top category. 

- [x] We should be able to Add / Edit / Delete a category. 

- [x] If we delete a top categories all children will be deleted. We should show a confirmation popup.

**Comment by andreisusanu** [comment]
Ready to be tested.

**Comment by mariusghitoiu** [comment]
Looks good.
