### ISSUE TITLE
Create routes for Gazda and implement design

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#57]
- [x] @andreisusanu Add dummy routes for Login Gazda flow 

- [x]  @nickraileanu once we have the routes, we need to implement the design 

Figma screens for hosts can be seen following the "Login Gazda" flow. 
https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1191%3A866&scaling=min-zoom

**Comment by andreisusanu** [comment]
I have seeded a new user with the Host role attached. Please use it for testing and development purposes.

Host email: host@helpforhealth.ro
Password: tesT

@nickraileanu please run
`php artisan migrate:fresh --seed`

**Comment by andreisusanu** [comment]
Layout, routes and blade templates are now prepared. @nickraileanu.
