### ISSUE TITLE
Setup Twill - CMS

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#76]
We should be able to edit static pages and various blocks of content from an admin, accesible at `ajutordeurgent.ro/cms`

- [x] we need to setup twill.

- [x] allow access only for admin, the same accounts. 

- [x] Add the ability to translate texts in both english and ro. 

- [x] we should be able to edit all static pages as follow: 
https://ajutordeurgenta.ro/ro/partners - we should have the ability to add partners and add specific blocks, as we did before. 
https://ajutordeurgenta.ro/ro/about - we can have distinct blocks in a dedicated page. Also FAQ can be a distinct type of content. 
https://ajutordeurgenta.ro/ro/media - this page should allow youtube embeds and the ability to add a description for each of them. We can create eventually a custom block for this. 
https://ajutordeurgenta.ro/ro/news - this will pull a feed from their website - nothing to do in twill
https://ajutordeurgenta.ro/ro/privacy-policy 
https://ajutordeurgenta.ro/ro/terms-and-conditions

**Comment by andreipetcu** [comment]
This should be done on branch issues/76_setup_twill
