### ISSUE TITLE
Database structure for accomodation

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#81]
With ticket #3 we have implemented the database structure for all except accomodation

With this ticket we have to update the database with tables to save data for properties, host properties relations and all this part we already have design for. 

https://ajutordeurgenta.ro/ro/get-involved
https://ajutordeurgenta.ro/admin/accommodation/detail

**Comment by andreisusanu** [comment]
**help_resources (eq. hepl_requests)**
- id
- full_name
- country_id
- city
- address
- phone_number
- email
- created_at
- updated_at
- deleted_at

**help_resource_type (eq. help_request_types)**
- id
- help_request_id
- request_type_id
- message
- created_at
- updated_at
- deleted_at

**resource_type (eq. help_type)**
- id
- name
- created_at
- updated_at

**Comment by andreisusanu** [comment]
**accommodations**
- id
- accommodation_type_id
- ownership_type
- is_fully_available
- max_guests
- available_rooms
- available_bathrooms
- is_kitchen_available
- is_parking_available
- description - VARCHAR 5000
- address_country_id
- address_city
- address_street
- address_building
- address_entry
- address_apartment
- address_floor
- address_postal_code
- is_smoking_allowed
- is_pet_allowed
- other_rules (text, 255)
- transport_subway_distance
- transport_bus_distance
- transport_railway_distance
- transport_other_details
- checkin_hour
- checkout_hour
- is_free (text, 255)
- general_fee
- created_at
- updated_at
- deleted_at

**accommodation_facility_type**
- id
- accommodation_id
- facility_type_id
- message (for other type only) (text, 255)
- created_at
- updated_at

**facility_types (seed)**
- id
- name
- created_at
- updated_at

**accommodation_types (seed)**
- id
- name
- created_at
- updated_at

**accommodation_photos**
- id
- accommodation_id
- path
- created_at
- updated_at
- deleted_at

**accommodation_availability**
- id
- accommodation_id
- start_date
- end_date
- created_at
- updated_at
- deleted_at

**Comment by mariusghitoiu** [comment]
Deployed in production. Ran migrations and seeders.
