### ISSUE TITLE
Implement 2FA

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#82]
We have to add the option for each user to enable 2FA. 

We should implement this for Google Authenticator compatible apps like. See the list at the beginning of [this article](https://scotch.io/tutorials/how-to-add-googles-two-factor-authentication-to-laravel).

- [x] This should be a distinct page in the dropdown menu, on name in the right, after login. 

- [x] Users should have the option to enable this and disable it. 

- [x] Here is a useful article https://www.mynotepaper.com/laravel-two-factor-authentication-with-google-authenticator

**Comment by andreipetcu** [comment]
Done on branch issues/82_2fa.

**Comment by mariusghitoiu** [comment]
Merged and deployed. Looks good. Small adjustments to the menu will be done with #146
