### ISSUE TITLE
EB - use platform hooks for deployment

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#83]
We want to update the deployment scripts on both, dev and production to use platforma hooks to run migrations. 

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

**Comment by andreisusanu** [comment]
Environment Health problems needs to be fixed. WIP

**Comment by andreisusanu** [comment]
Fixed.
