### ISSUE TITLE
Backed: help resource details for accommodation

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#90]
With #88 we have handled the details for the other types of help resources. 
With this issues we should handle the help resource details page for accommodation.

Figma design here https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1196%3A7726&scaling=min-zoom 

Html implementation here https://ajutordeurgenta.ro/admin/accommodation/detail 

- [x] A user that apply to offer accommodation can have multiple resources units. To keep it simple we show a list with all properties (below the help resource details) like we do in Host account here https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1191%3A1271&scaling=min-zoom instead of showing property details directly. On the accommodation unit box we will have a View button that goes to the details page of the unit. It will be the same view we have if we go from "Spatii de cazare >> Details" 

- [x] Notes will be handled with this issue https://github.com/code4romania/help-for-health/issues/92

**Comment by andreisusanu** [comment]
To keep it simple, we need to add the list of Accommodations on the user profile page.

https://www.figma.com/proto/HV4LBHc1aXUfNKbVoJcn9uQ1/Help-for-Health?node-id=1291%3A1244&scaling=min-zoom

WIP

**Comment by mariusghitoiu** [comment]
@andreisusanu @wasile we should also list the accommodations in help resource details page. 
Similar to how we list them on user profile to make it easier for admin to access them. 

@wasile I will reassign this issue to you

**Comment by mariusghitoiu** [comment]
Looks good.
