### ISSUE TITLE
Cities filters - consider selected country

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#96]
We should add an extra filter to cities everywhere where we have countries and cities as filters. 
Once a country is selected we should filter only the cities associated with entities that are associated with selected country.

Ex: Help requests -> once we set a filter for Romania -> we should Show only cities that are associated with help requests coming from Romania.

**Comment by wasile** [comment]
for that we need to change cities to be selected from a dropdown (now it's plain text, we can't do the correlation)

**Comment by mariusghitoiu** [comment]
We can do it via help requests, we don't need to have a connection between countries and cities.

**Comment by wasile** [comment]
Ok. i think i got it.

**Comment by mariusghitoiu** [comment]
Looks good.
