### ISSUE TITLE
Upgrade phone validation with country prefix and more

### ISSUE THREAD

**Issue by mariusghitoiu** [code4romania/help-for-health#99]
The phone number from [here](https://ajutordeurgenta.ro/ro/get-involved ) can't be validated for Romania only, because can be used by people from all over the world. 

We should implement the same concept, with country prefix like here 
https://chestionar.stsisp.ro/introducere-telefon

https://github.com/giggsey/libphonenumber-for-php

**Comment by mariusghitoiu** [comment]
[countries.txt](https://github.com/code4romania/help-for-health/files/5225617/countries.txt)

**Comment by wasile** [comment]
you have torun the PhonePrefixSeeder

`php artisan db:seed --class=PhonePrefixSeeder`

**Comment by mariusghitoiu** [comment]
Looks good.
